apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: app1
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: 547365428614.dkr.ecr.us-east-2.amazonaws.com/conduco-screeners
          ports: 
            - containerPort: 4000
            
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  ports:
  - port: 4000
  selector:
    app: app1


