apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: app1
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: 547365428614.dkr.ecr.us-east-2.amazonaws.com/conduco-screeners
          ports: 
            - containerPort: 4000
            
      volumeMounts:
        - name: screeners-qa-local-coffee
          mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
          readOnly: true
      volumes:      
      env:
        - name: CONDUCO_CLIENT
          value: screeners
        - name: SECRETS_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: GET_HOSTS_FROM
          value: dns
        - name: AWS_REGION
          value: us-east-1
        - name: NODE_ENV
          value: production
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret_access_key
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  ports:
  - port: 4000
  selector:
    app: app1


